TreatShop/Models/Flavor.cs
using System.ComponentModel.DataAnnotations;

namespace TreatShop.Models 
{
  public class Flavor 
  {
    public int FlavorId { get; set; }

    [Required(ErrorMessage = "The Flavor name field can't be empty!")]
    public string Name { get; set; }
    public List<TreatFlavor> JoinEntities { get; set; }
  }
}

TreatShop/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using TreatShop.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace TreatShop.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly TreatShopContext _db;
    public FlavorsController(TreatShopContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> flavors = _db.Flavors.ToList();
      return View(flavors);
    }

    [Authorize(Roles = "admin")]
    public ActionResult Create()
    {
      return View();
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    
    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
      .Include(flavor => flavor.JoinEntities)
      .ThenInclude(join => join.Treat)
      .FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize(Roles = "admin")]
    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "admin")]
    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize(Roles = "admin")]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
#nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TreatShop/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model TreatShop.Models.Flavor;

<div class="page-header">
  <h1>Add a Treat</h1>
  <hr>
</div>

<div id="form">
  <h4>Add a Treat to this Flavor: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select Treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
  }
</div>

TreatShop/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model TreatShop.Models.Flavor;

<div class="page-header">
  <h1>Create a Flavor</h1>
  <hr>
</div>

<div id="form">
  <p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })
  </p>

  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    <input type="submit" value="Add" />
  }
  <p>@Html.ActionLink("Back to List", "Index")</p>
</div>

TreatShop/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

<div class="page-header">
  <h1>Delete</h1>
  <hr>
</div>

@model TreatShop.Models.Flavor;

<div id="form">
  <h2>Are you sure you want to delete this?</h2>

  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
</div>

TreatShop/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using TreatShop.Models;
@model TreatShop.Models.Flavor;


<div class="page-header">
  <h1>Flavor Details</h1>
  <hr>
</div>

<div id="form">
  <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
  @if (@Model.JoinEntities.Count == 0)
  {
    <p>This Flavor does not belong to any Treats</p>
  }
  else
  {
    @foreach (TreatFlavor join in Model.JoinEntities)
    {
      <h3>Treats: @join.Treat.Name</h3>
      @using (Html.BeginForm("DeleteJoin", "Flavors"))
      {
        @Html.Hidden("joinId", @join.TreatFlavorId)
        <input type="submit" value="Delete" class="btn btn-danger"/>
      }
    }
  }
</div>
<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Edit this Flavor", "Edit", new { id = Model.FlavorId})</p>
<p>@Html.ActionLink("Delete this Flavor", "Delete", new { id = Model.FlavorId})</p>

TreatShop/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TreatShop.Models.Flavor;

<div class="page-header">
  <h1>Edit</h1>
  <hr>
</div>

<div id="form">
  <h4>Flavor: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
  }
</div>

TreatShop/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="page-header">
  <h1>Flavors</h1>
  <hr>
</div>

@using TreatShop.Models;

<div id="form">
  <h3><u>List of Flavors</u></h3>
  @if (Model.Count == 0)
  {
    <h3>No Flavors have been added yet</h3>
  }
  else
  {
    <ul>
      @foreach (Flavor flavor in Model)
      {
        <div class="card" style="width: 10rem;">
          <img src="https://img.icons8.com/emoji/512/tongue-emoji.png" class="card-img-top" alt="example flavor image">
          <div class="card-body">
            <h5 class="card-title"><strong>@flavor.Name</strong></h5>
            <p class="btn btn-light">@Html.ActionLink("Details", "Details", "Flavors", new { id = @flavor.FlavorId})</p>
          </div>
        </div>
      }
    </ul>
  }
  <p>@Html.ActionLink("Create a new Flavor", "Create")</p>
</div>