TreatShop/Models/Treat.cs
using System.ComponentModel.DataAnnotations;

namespace TreatShop.Models 
{
  public class Treat 
  {
    public int TreatId { get; set; }

    [Required(ErrorMessage = "The Treat name field can't be empty!")]
    public string Name { get; set; }
    public List<TreatFlavor> JoinEntities { get; set; }
  }
}

TreatShop/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using TreatShop.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace TreatShop.Controllers
{
  public class TreatsController : Controller
  {
    private readonly TreatShopContext _db;
    public TreatsController(TreatShopContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Treat> treats = _db.Treats.ToList();
      return View(treats);
    }

    [Authorize(Roles = "admin")]
    public ActionResult Create()
    {
      return View();
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
      .Include(treat => treat.JoinEntities)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize(Roles = "admin")]
    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize(Roles = "admin")]
    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize(Roles = "admin")]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirm(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    
    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TreatShop/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model TreatShop.Models.Treat;

<div class="page-header">
  <h1>Add a Flavor </h1>
  <hr>
</div>

<div id="form">
  <h4>Add a Flavor to this Treat: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select Flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
  }
</div>

TreatShop/Views/Treats/Create.cshtml
@{
	Layout = "_Layout";
}

@model TreatShop.Models.Treat

<div class="page-header">
	<h1>Create a Treat</h1>
	<hr>
</div>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<div id="form">
	@using (Html.BeginForm())
	{
		@Html.LabelFor(model => model.Name)<br>
		@Html.TextBoxFor(model => model.Name)
		<input type="submit" value="Add" />
	}
</div>

<p>@Html.ActionLink("Back to List", "Index")</p>

TreatShop/Views/Treats/Delete.cshtml
@{
	Layout = "_Layout";
}

@model TreatShop.Models.Treat;

<div class="page-header">
	<h1>Delete</h1>
	<hr>
</div>

<h3>Are you sure?</h3>
<div id="form">
	@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
	@using (Html.BeginForm())
	{
		<input type="submit" value="Delete" class="btn btn-danger" />
	}
</div>
@Html.ActionLink("Back to List", "Index")

TreatShop/Views/Treats/Details.cshtml
@{
	Layout = "_Layout";
}

@model TreatShop.Models.Treat;
@using TreatShop.Models;


<div class="page-header">
	<h1>Treat Details</h1>
	<hr>
</div>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<div id="form">
	@if (@Model.JoinEntities.Count == 0)
	{
		<p>This Treat has no Flavors</p>
	}
	else
	{
		@foreach (TreatFlavor join in Model.JoinEntities)
		{
			<h3>Flavors: @join.Flavor.Name</h3>
			@using (Html.BeginForm("DeleteJoin", "Treats"))
			{
				@Html.Hidden("joinId", @join.TreatFlavorId)
				<input type="submit" value="Delete" class="btn btn-danger" />
			}
		}
	}
</div>

<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Edit this Treat", "Edit", new { id = Model.TreatId })</p>
  <p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>

TreatShop/Views/Treats/Edit.cshtml
@{
	Layout = "_Layout";
}

@model TreatShop.Models.Treat;

<div class="page-header">
	<h1>Edit</h1>
	<hr>
</div>

<div id="form">
	<h4>Edit this Treat: @Html.DisplayFor(model => model.Name)</h4>
	@using (Html.BeginForm())
	{
		@Html.HiddenFor(model => model.TreatId)

		@Html.LabelFor(model => model.Name)<br>
		@Html.EditorFor(model => model.Name)
		<input type="submit" value="Save" />
	}
</div>
<p>@Html.ActionLink("Back to list", "Index")</p>

TreatShop/Views/Treats/Index.cshtml
@{
	Layout = "_Layout";
}

<div class="page-header">
	<h1>Treats</h1>
	<hr>
</div>

@using TreatShop.Models;

<h3><u>List of Treats</u></h3>

<div id="form">
	@if (Model.Count == 0)
	{
		<h3>No Treats have been added yet</h3>
	}
	else
	{
		<ul>
			@foreach (Treat treat in Model)
			{
				<div class="card" style="width: 10rem;">
					<img
				src="https://img.icons8.com/external-icongeek26-outline-colour-icongeek26/512/external-treat-pet-care-icongeek26-outline-colour-icongeek26.png"
				class="card-img-top" alt="example treat image">
					<div class="card-body">
						<h5 class="card-title"><strong>@treat.Name</strong></h5>
						<p class="btn btn-light">@Html.ActionLink("Details", "Details", "Treats", new { id = @treat.TreatId})</p>
					</div>
				</div>
			}
		</ul>
	}
	<p>@Html.ActionLink("Create a new Treat", "Create")</p>
</div>